# suppress inspection "UnusedProperty" for whole file
# ********************************
spring.application.name=anibl
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.file.name=${spring.application.name}.log
# ********************************
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
# ********************************
# JWT - Note: "secret-key" must be a 256-bit HMAC hash.
# ********************************
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_MS:3600000}
# ********************************
